In [3]:
import sys
from scipy import linalg
import numpy as np

# Problem 1
Using BLAS/LAPACK and the following system of linear equations:

$x_1 - x_2  + 3x_4 = 8$

$2x_1 + x_2 + 2x_3 + x_4 = 11$

$2x_1 - 3x_2 - 2x_3  = -8 $

$3x_2 - 2x_3 + 4x_4 = 14 $

## Part (a)
Find the coefficient matrix, matrix inverse and the determinant

Given the linear system $A.x = B$, let $A$ be the coefficients matrix, then the coefficients matrix will be given by:

In [4]:
A = np.matrix([[1, -1, 0, 3], [2, 1, 2, 1], [2, -3, -2, 0], [0, 3, -2, 4]])
print(A)

[[ 1 -1  0  3]
 [ 2  1  2  1]
 [ 2 -3 -2  0]
 [ 0  3 -2  4]]


Then, the matrix inverse $A^{-1}$ can be obtained using BLAS as following:

In [5]:
Ainverse = linalg.inv(A)
print(Ainverse)

[[-0.21875    0.34375    0.265625   0.078125 ]
 [-0.28125    0.15625   -0.015625   0.171875 ]
 [ 0.203125   0.109375  -0.2109375 -0.1796875]
 [ 0.3125    -0.0625    -0.09375    0.03125  ]]


The determinant $|A|$ is computed with the following code

In [6]:
detA = linalg.det(A)
print(detA)

-128.0


## Part (b)
Find the inverse of the coefficients matrix

In [7]:
print(Ainverse)

[[-0.21875    0.34375    0.265625   0.078125 ]
 [-0.28125    0.15625   -0.015625   0.171875 ]
 [ 0.203125   0.109375  -0.2109375 -0.1796875]
 [ 0.3125    -0.0625    -0.09375    0.03125  ]]


## Part (c)
Now, using an iterative algorithm, find the matrix inverse

In [9]:
def inverseUsingGauss(MatrixInput):
    (MatrixInput)

print(inverseUsingGauss(2))

1
