In [1]:
import sys
from scipy import linalg
import numpy as np

# Problem 1
Using BLAS/LAPACK and the following system of linear equations:

$x_1 - x_2  + 3x_4 = 8$

$2x_1 + x_2 + 2x_3 + x_4 = 11$

$2x_1 - 3x_2 - 2x_3  = -8 $

$3x_2 - 2x_3 + 4x_4 = 14 $

## Part (a)
Find the coefficient matrix, matrix inverse and the determinant

Given the linear system $A.x = B$, let $A$ be the coefficients matrix, then the coefficients matrix will be given by:

In [2]:
A = np.matrix([[1, -1, 0, 3], [2, 1, 2, 1], [2, -3, -2, 0], [0, 3, -2, 4]])
print(A)

[[ 1 -1  0  3]
 [ 2  1  2  1]
 [ 2 -3 -2  0]
 [ 0  3 -2  4]]


Then, the matrix inverse $A^{-1}$ can be obtained using BLAS as following:

In [3]:
Ainverse = linalg.inv(A)
print(Ainverse)

[[-0.21875    0.34375    0.265625   0.078125 ]
 [-0.28125    0.15625   -0.015625   0.171875 ]
 [ 0.203125   0.109375  -0.2109375 -0.1796875]
 [ 0.3125    -0.0625    -0.09375    0.03125  ]]


The determinant $|A|$ is computed with the following code

In [4]:
detA = linalg.det(A)
print(detA)

-128.0


## Part (b)
Find the inverse of the coefficients matrix

In [5]:
print(Ainverse)

[[-0.21875    0.34375    0.265625   0.078125 ]
 [-0.28125    0.15625   -0.015625   0.171875 ]
 [ 0.203125   0.109375  -0.2109375 -0.1796875]
 [ 0.3125    -0.0625    -0.09375    0.03125  ]]


## Part (c)
Now, using an iterative algorithm, find the matrix inverse

In [9]:
from inverseGauss import * #See inverseGauss.py at the end of this file for the full implementation of the algorithm
print(inverseUsingGauss(A, False))

Matrix is not square, this algorithm does not work! :(


TypeError: 'NoneType' object is not subscriptable

## Part (d)
Solve the system ussing $x = A^{-1} B$

In [21]:
B = np.matrix([[8] ,[11], [-8], [14]])
solution = Ainverse*B
print(solution)

[[1.]
 [2.]
 [2.]
 [3.]]


## Part (e)
Solve the system ussing Solve

In [22]:
print(linalg.solve(A,B))

[[1.]
 [2.]
 [2.]
 [3.]]


## Part (f)
Solve the system ussing an iterative method

## Part (g)
Find the eigenvalues and eigenvectors of the coefficients matrix