In [16]:
import sys
from scipy import linalg
import numpy as np

# Problem 1
Using BLAS/LAPACK and the following system of linear equations:

$x_1 - x_2  + 3x_4 = 8$

$2x_1 + x_2 + 2x_3 + x_4 = 11$

$2x_1 - 3x_2 - 2x_3  = -8 $

$3x_2 - 2x_3 + 4x_4 = 14 $

## Part (a)
Find the coefficient matrix, matrix inverse and the determinant

Given the linear system $A.x = B$, let $A$ be the coefficients matrix, then the coefficients matrix will be given by:

In [17]:
A = np.array([[1, -1, 0, 3], [2, 1, 2, 1], [2, -3, -2, 0], [0, 3, -2, 4]])
print(A)

[[ 1 -1  0  3]
 [ 2  1  2  1]
 [ 2 -3 -2  0]
 [ 0  3 -2  4]]


Then, the matrix inverse $A^{-1}$ can be obtained using BLAS as following:

In [18]:
Ainverse = linalg.inv(A)
print(Ainverse)

[[-0.21875    0.34375    0.265625   0.078125 ]
 [-0.28125    0.15625   -0.015625   0.171875 ]
 [ 0.203125   0.109375  -0.2109375 -0.1796875]
 [ 0.3125    -0.0625    -0.09375    0.03125  ]]


The determinant $|A|$ is computed with the following code

In [19]:
detA = linalg.det(A)
print(detA)

-128.0


## Part (b)
Find the inverse of the coefficients matrix

In [20]:
print(Ainverse)

[[-0.21875    0.34375    0.265625   0.078125 ]
 [-0.28125    0.15625   -0.015625   0.171875 ]
 [ 0.203125   0.109375  -0.2109375 -0.1796875]
 [ 0.3125    -0.0625    -0.09375    0.03125  ]]


## Part (c)
Now, using an iterative algorithm, find the matrix inverse

In [21]:
from iterativeMethods import *
print(inverseUsingGauss(A))

[[-0.21875    0.34375    0.265625   0.078125 ]
 [-0.28125    0.15625   -0.015625   0.171875 ]
 [ 0.203125   0.109375  -0.2109375 -0.1796875]
 [ 0.3125    -0.0625    -0.09375    0.03125  ]]


## Part (d)
Solve the system ussing $x = A^{-1} B$

In [22]:
B = np.array([[8] ,[11], [-8], [14]])
solution = Ainverse*B
print(solution)

[[-1.75      2.75      2.125     0.625   ]
 [-3.09375   1.71875  -0.171875  1.890625]
 [-1.625    -0.875     1.6875    1.4375  ]
 [ 4.375    -0.875    -1.3125    0.4375  ]]


## Part (e)
Solve the system ussing Solve

In [23]:
print(linalg.solve(A,B))

[[1.]
 [2.]
 [2.]
 [3.]]


## Part (f)
Solve the system ussing an iterative method

In [24]:
BAux = B.flatten()
print(solveUssingIterative(A, BAux))

[1.00005967 2.00004749 1.99996482 2.9999557 ]


## Part (g)
Find the eigenvalues and eigenvectors of the coefficients matrix

In [25]:
eigens = linalg.eig(A)
print("Eigen values:")
print(eigens[0])
print("Eigen vectors:")
print(eigens[1])

Eigen values:
[-2.08120832+0.j          0.31062061+3.34182877j  0.31062061-3.34182877j
  5.4599671 +0.j        ]
Eigen vectors:
[[ 0.47287114+0.j          0.02294322+0.52054251j  0.02294322-0.52054251j
   0.45825885+0.j        ]
 [ 0.29537001+0.j          0.57350275+0.j          0.57350275-0.j
   0.37386625+0.j        ]
 [-0.734312  +0.j         -0.02364408+0.48476132j -0.02364408-0.48476132j
  -0.02749088+0.j        ]
 [-0.38721483+0.j         -0.39395926-0.09405965j -0.39395926+0.09405965j
   0.80589522+0.j        ]]
